[package]
name = "rs-xk"
version = "0.1.0"
authors = ["anticore <slimedev@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
libc = { version = "0.2", default-features = false }